// let's imagine this file is autogenerated from the backend
// ideally, we want to keep these api related types in sync
// with the backend instead of manually writing them out

/** 백엔드 자동 생성을 염두해둔 기본 엔티티 정의 */
export type BaseEntity = {
  id: string;
  createdAt: number;
};

/** Entity 헬퍼 타입 */
export type Entity<T> = {
  [K in keyof T & BaseEntity]: (T & BaseEntity)[K];
}

export type Meta = {
  page: number;
  total: number;
  totalPages: number;
};

/** 확장성을 위해 별도 타입으로 분리 */
export type UserRole = 'ADMIN' | 'USER';

export type User = Entity<{
  firstName: string;
  lastName: string;
  email: string;
  role: UserRole;
  teamId: string;
  bio: string;
}>;

export type AuthResponse = {
  jwt: string;
  user: User;
};

export type Team = Entity<{
  name: string;
  description: string;
}>;

export type Discussion = Entity<{
  title: string;
  body: string;
  teamId: string;
  author: User;
  public: boolean;
}>;

export type Comment = Entity<{
  body: string;
  discussionId: string;
  author: User;
}>;

/** 목록 조회를 위한 공통 래퍼 타입 */
export type ApiResponse<T> = {
    data: T;
    meta?: Meta;
}
